// Spanish translations for report commands and messages (F6.8).
export const ES = {
  'list local reports': 'listar reportes locales',
  'No reports yet.': 'Aún no hay reportes.',
  'Local reports:': 'Reportes locales:',
  'read a local report': 'leer un reporte local',
  'Usage: blackbrake report show <name>': 'Uso: blackbrake report show <nombre>',
  'Report not found.': 'Reporte no encontrado.',
  'Cannot read report.': 'No se puede leer el reporte.',
  'validate a report file': 'validar un archivo de reporte',
  'Usage: blackbrake report check <path>': 'Uso: blackbrake report check <ruta>',
  'Report has {n} problems:': 'El reporte tiene {n} problemas:',
  'Report is valid.': 'El reporte es válido.',
  'Cannot read file.': 'No se puede leer el archivo.',
  'prepare to send a report': 'preparar para enviar un reporte',
  'Usage: blackbrake report send (product|security) <name>': 'Uso: blackbrake report send (product|security) <nombre>',
  'Report prepared. Your mail client should open.': 'Reporte preparado. Tu cliente de correo debería abrir.',
  'Could not open mail client.': 'No se pudo abrir el cliente de correo.',
  'Cannot prepare report.': 'No se puede preparar el reporte.',
  'delete a local report': 'eliminar un reporte local',
  'Usage: blackbrake report delete <name>': 'Uso: blackbrake report delete <nombre>',
  'Report deleted.': 'Reporte eliminado.',
  'Cannot delete report.': 'No se puede eliminar el reporte.',
  'Usage: blackbrake report (list|show|check|send|delete) [args]': 'Uso: blackbrake report (list|show|check|send|delete) [args]',
};
